import type { ComponentAiMetadata } from "@/types/ai-metadata";

export const inputAiMetadata: ComponentAiMetadata = {
  component: "Input",
  purpose: "Data Input",
  usage: [
    "Login",
    "Search",
    "Form Field",
    "Email",
    "Password",
    "Number Entry",
  ],
  avoid: ["Long-form rich text", "Multi-select lists"],
  aliases: [
    "Text Field",
    "Email Input",
    "Password Input",
    "Search Input",
    "입력창",
    "이메일",
    "비밀번호",
  ],
  dependencies: ["Color", "Typography", "Spacing", "Radius", "Motion", "Density"],
  variants: ["Text", "Email", "Password", "Search", "Number"],
  sizes: ["S", "M", "L"],
  states: ["Default", "Focus", "Error", "Disabled"],
  accessibility: [
    "Label association",
    "Keyboard Navigation",
    "Focus Ring",
    "ARIA invalid on Error",
    "Contrast AA",
  ],
  aiRules: [
    {
      id: "input.email.login",
      when: { anyOf: ["email", "이메일", "아이디", "login", "로그인"] },
      then: { component: "Input", variant: "Email" },
      reason: "Login / identity fields prefer Email.",
    },
    {
      id: "input.password",
      when: { anyOf: ["password", "비밀번호", "패스워드"] },
      then: { component: "Input", variant: "Password" },
      reason: "Credential secrets use Password.",
    },
    {
      id: "input.search",
      when: { anyOf: ["search", "검색", "filter", "필터"] },
      then: { component: "Input", variant: "Search" },
      reason: "Lookup fields use Search.",
    },
  ],
  figmaMapping: [
    "Input/Text/M/Default",
    "Input/Email/M/Default",
    "Input/Password/M/Default",
    "Input/Search/M/Focus",
    "Input/Text/M/Error",
  ],
  confidence: 0.92,
  priority: 90,
  category: "input",
  compatibleWith: ["Button", "Form", "Checkbox", "Card"],
  generatedByAI: false,
  version: "1.0.0",
};
